package com.paynearme.callbacks.server;

import java.util.Map;

/**
 * Exception generated by an invalid signature event. This may be handled directly by the handlers, or the servlet.
 */
public class InvalidSignatureException extends Exception {
    public InvalidSignatureException() {
        super("Invalid Signature (or none found)");
    }

    public InvalidSignatureException(String signature, String expected, Map<String, String[]> params) {
        super(exceptionMessage(signature, expected, params));
    }

    private static String exceptionMessage(String signature, String expected, Map<String, String[]> params) {
        StringBuilder builder = new StringBuilder("Invalid Signature: ");
        builder.append(signature).append(" (expected: ").append(expected).append(")");
        builder.append("\nParameter Map:");
        for (String key : params.keySet()) {
            String[] value = params.get(key);
            builder.append("\n\t")
                    .append(key).append(" = ");
            if (value != null && value.length != 0) {
                builder.append(value[0]);
            } else {
                builder.append("null");
            }
        }

        return builder.toString();
    }
}
